name: Bug report
description: File a software bug report
type: Bug

body:

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Describe the problem. Provide instructions on how to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: snap-version
    attributes:
      label: Snap version
      description: Provide the output of the following command: `<inference-snap> version`
      render: shell
