name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      working-directory: docs
      run: make install
    - name: Lint Markdown
      working-directory: docs
      run: make lint-md
